### ISSUE TITLE
Can send response message with <Message>

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/anonymous-communications-rails#11]
[In the reservations controller](https://github.com/TwilioDevEd/anonymous-communications-rails/blob/master/app/controllers/reservations_controller.rb#L54-L65) you can send a message to the host by sending back a `<Message>` TwiML where the `to` attribute is the intended receipient (e.g. it doesn't have to be a reply to the sender of the message).

This would eliminate an extra HTTP request, and looks like an extra database read too. Would also reduce code in the model.

**Comment by jarodreyes** [comment]
Fixed: https://github.com/TwilioDevEd/anonymous-communications-rails/commit/15c754a48abf52096ecc611f97364dc4bd134972

**Comment by kwhinnery** [comment]
The other bit in the controller still sends the message via the model code.

**Comment by jarodreyes** [comment]
Well sure, but in that case we still have to do the extra ActiveRecord query, so there is little point in pulling that out.

**Comment by jarodreyes** [comment]
Okay made the change, updated the tutorial. Leaving the model code, since it still has utility.
