### ISSUE TITLE
refactor provision_phone_number

### ISSUE THREAD

**Issue by GregBaugues** [TwilioDevEd/anonymous-communications-rails#4]
[Here](https://github.com/TwilioDevEd/anonymous-communications-rails/blob/master/app/models/reservation.rb#L63). I would break this up into several pieces. May go so far as to create my own Twilio module with helper functions that I could reuse throughout the app. For instance, creating a twilio client. 

It feels weird to have the code for provisioning a number inside of the reservation model. 

So maybe could do something like: 

WIP

**Comment by jarodreyes** [comment]
Duplicate.
