### ISSUE TITLE
Misc Style Suggestions

### ISSUE THREAD

**Issue by GregBaugues** [TwilioDevEd/anonymous-communications-rails#5]
### Enumberables

Use ```numbers.first``` over ```numbers[0]```
Use ```if @numbers.empty?``` over ```if not @numbers.any?```

### Ternary

```ruby
@app_number = from_number.nil? ? ENV['TWILIO_NUMBER'] : from_number
```

over inline if: 

```ruby
@app_number = if from_number.nil? then ENV['BARISTA_NUMBER'] else from_number end
```

### Saving

Use 

```ruby 
player.update(name: 'Tom Brady') 
```

over 

```ruby
player.name = 'Tom Brady'
player.save
```

**Comment by jarodreyes** [comment]
Thanks! Fixed in: https://github.com/TwilioDevEd/anonymous-communications-rails/commit/3dfb70fb61089a4d8906a70ddc2e0da960829f75
